// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AyHmN6wYUxxkmEBl7f82EHql0L0SAbs',
    appId: '1:4770398777:web:3190239d14e9b7fe3243e8',
    messagingSenderId: '4770398777',
    projectId: 'mind-note-ai',
    authDomain: 'mind-note-ai.firebaseapp.com',
    storageBucket: 'mind-note-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9hD_GBt5b6loosFqP8rHtFYAZs0GRFM',
    appId: '1:4770398777:android:65e944feecca294d3243e8',
    messagingSenderId: '4770398777',
    projectId: 'mind-note-ai',
    storageBucket: 'mind-note-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ziNsXNUy6OfpJNnOJ5d70d0Pknp1nHU',
    appId: '1:4770398777:ios:5e0034d96e7ea8993243e8',
    messagingSenderId: '4770398777',
    projectId: 'mind-note-ai',
    storageBucket: 'mind-note-ai.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ziNsXNUy6OfpJNnOJ5d70d0Pknp1nHU',
    appId: '1:4770398777:ios:5e0034d96e7ea8993243e8',
    messagingSenderId: '4770398777',
    projectId: 'mind-note-ai',
    storageBucket: 'mind-note-ai.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8AyHmN6wYUxxkmEBl7f82EHql0L0SAbs',
    appId: '1:4770398777:web:cd0e39e0592659e33243e8',
    messagingSenderId: '4770398777',
    projectId: 'mind-note-ai',
    authDomain: 'mind-note-ai.firebaseapp.com',
    storageBucket: 'mind-note-ai.firebasestorage.app',
  );
}
